using SightReadingHelper.Controls;
using SightReadingHelper.Models;
using SightReadingHelper.Services;

namespace SightReadingHelper;

public partial class PracticePage : ContentPage
{
    private const int SampleRate = 44100;
    private const double HoldProgressDecayPerSecond = 1.5d;

    private readonly PracticeDataService _practiceDataService;
    private readonly ExerciseGeneratorService _exerciseGeneratorService;
    private readonly PitchDetectionService _pitchDetectionService;
    private readonly PitchCalibrationService _pitchCalibrationService;
    private readonly NoteJudgmentService _noteJudgmentService;
    private readonly IAudioInputService _audioInputService;

    private InstrumentProfile? _instrument;
    private PracticeSettings? _settings;
    private PracticeOptionsConfig _practiceOptions = new();
    private CalibrationProfile? _calibration;
    private PracticeExercise? _exercise;
    private int _currentNoteIndex;
    private int _sessionCorrectCount;
    private int _completedExerciseCount;
    private bool _isListening;
    private bool _isPageVisible;
    private int? _lastDetectedDisplayMidiNote;
    private double _holdProgress;
    private DateTimeOffset _lastPitchUpdateAt = DateTimeOffset.MinValue;
    private readonly StaffNotationDrawable _notationDrawable = new();

    public PracticePage(
        PracticeDataService practiceDataService,
        ExerciseGeneratorService exerciseGeneratorService,
        PitchDetectionService pitchDetectionService,
        PitchCalibrationService pitchCalibrationService,
        NoteJudgmentService noteJudgmentService,
        IAudioInputService audioInputService)
    {
        InitializeComponent();
        _practiceDataService = practiceDataService;
        _exerciseGeneratorService = exerciseGeneratorService;
        _pitchDetectionService = pitchDetectionService;
        _pitchCalibrationService = pitchCalibrationService;
        _noteJudgmentService = noteJudgmentService;
        _audioInputService = audioInputService;
        _audioInputService.SamplesAvailable += OnSamplesAvailable;
        NotationView.Drawable = _notationDrawable;
    }

    protected override async void OnAppearing()
    {
        base.OnAppearing();
        _isPageVisible = true;
        await LoadPracticeAsync();
        await StartListeningAsync();
    }

    private async Task LoadPracticeAsync()
    {
        _settings = await _practiceDataService.GetPracticeSettingsAsync();
        _practiceOptions = await _practiceDataService.GetPracticeOptionsAsync();
        _instrument = await _practiceDataService.GetSelectedInstrumentAsync();
        _calibration = await _practiceDataService.GetCalibrationAsync(_instrument.InstrumentName);

        PracticeSummaryLabel.Text = $"Active instrument: {_instrument.InstrumentName} ({_instrument.DefaultClef}).";
        PracticeSettingsLabel.Text = $"{_settings.ExerciseLength} notes, ±{_settings.ToleranceCents} cents, {GetHoldRequirementLabel(_settings)}, {GetAccidentalModeLabel(_settings)}, {(_settings.UseBeginnerRange ? "beginner" : "full")} range, {GetBaseJumpLabel(_practiceOptions, _instrument, _settings.MaxBaseNoteJump ?? 1).ToLowerInvariant()}, {_instrument.BaseNoteGroupLabel}: {GetAllowedBaseNotesLabel(_settings, _instrument)}.";

        if (_exercise is null || _exercise.InstrumentName != _instrument.InstrumentName || _exercise.Notes.Count != _settings.ExerciseLength)
        {
            GenerateExercise(isAutoGenerated: false, resetSession: true);
        }
        else
        {
            RefreshPracticeView();
        }
    }

    private void GenerateExercise(bool isAutoGenerated, bool resetSession)
    {
        if (_instrument is null || _settings is null)
        {
            return;
        }

        if (resetSession)
        {
            _sessionCorrectCount = 0;
            _completedExerciseCount = 0;
        }

        _exercise = _exerciseGeneratorService.GenerateExercise(_instrument, _settings);
        _currentNoteIndex = 0;
        ResetStableCandidate();
        JudgmentLabel.Text = isAutoGenerated
            ? "Nice. Keep going."
            : "Endless practice ready. Play the highlighted note.";
        JudgmentLabel.TextColor = GetColor("Gray900");
        RefreshPracticeView();
    }

    private void RefreshPracticeView()
    {
        if (_exercise is null || _settings is null)
        {
            return;
        }

        RenderExercise();

        if (_currentNoteIndex >= _exercise.Notes.Count)
        {
            ExpectedPitchLabel.Text = "Loading the next notes.";
            DetectedPitchSummaryLabel.Text = "Endless practice is continuing.";
            ProgressLabel.Text = $"Sets completed: {_completedExerciseCount} | Total correct: {_sessionCorrectCount}";
            ExerciseProgressBar.Progress = 1;
            return;
        }

        var currentNote = _exercise.Notes[_currentNoteIndex];
        ExpectedPitchLabel.Text = _settings.ShowNoteName
            ? $"Target: {PitchMath.ToDisplayNoteName(currentNote.DisplayNoteName)} | {currentNote.FrequencyHz:0.0} Hz"
            : $"Target pitch: {currentNote.FrequencyHz:0.0} Hz";
        DetectedPitchSummaryLabel.Text = _isListening
            ? $"Listening for a stable pitch. {GetHoldRequirementLabel(_settings)}."
            : "Microphone starts automatically when this page opens.";
        ProgressLabel.Text = $"Set {_completedExerciseCount + 1} | Note {_currentNoteIndex + 1} of {_exercise.Notes.Count} | Total correct: {_sessionCorrectCount}";
        ExerciseProgressBar.Progress = _exercise.Notes.Count == 0
            ? 0
            : (double)_currentNoteIndex / _exercise.Notes.Count;
    }

    private void RenderExercise()
    {
        if (_exercise is null)
        {
            return;
        }

        _notationDrawable.Notes = _exercise.Notes;
        _notationDrawable.Clef = _exercise.Clef;
        _notationDrawable.CurrentNoteIndex = _currentNoteIndex;
        _notationDrawable.GhostMidiNote = _lastDetectedDisplayMidiNote;
        _notationDrawable.HoldProgress = _holdProgress;
        NotationView.WidthRequest = StaffNotationDrawable.GetRequiredWidth(_exercise.Notes.Count);
        NotationView.Invalidate();
    }

    private async Task StartListeningAsync()
    {
        if (_isListening)
        {
            return;
        }

        if (!_isPageVisible)
        {
            return;
        }

        try
        {
            ResetStableCandidate();
            await _audioInputService.StartAsync(SampleRate);
            _isListening = true;
            MicrophoneStatusLabel.Text = "Listening...";
            RefreshPracticeView();
        }
        catch (Exception ex)
        {
            MicrophoneStatusLabel.Text = "Could not start the microphone.";
            await DisplayAlert("Microphone error", ex.Message, "OK");
        }
    }

    private async Task StopListeningAsync()
    {
        if (!_isListening)
        {
            return;
        }

        await _audioInputService.StopAsync();
        _isListening = false;
        MicrophoneStatusLabel.Text = "Stopped.";
        ResetStableCandidate();
        RefreshPracticeView();
    }

    private void OnSamplesAvailable(float[] samples, int sampleRate)
    {
        var rawDetectedPitch = _pitchDetectionService.AnalyzeSamples(samples, sampleRate);
        var detectedPitch = _pitchCalibrationService.ApplyCalibration(rawDetectedPitch, _calibration);
        MainThread.BeginInvokeOnMainThread(() => HandleDetectedPitch(detectedPitch));
    }

    private void HandleDetectedPitch(PitchDetectionResult detectedPitch)
    {
        if (!_isListening || _exercise is null || _settings is null || _currentNoteIndex >= _exercise.Notes.Count)
        {
            return;
        }

        MicrophoneLevelBar.Progress = Math.Clamp(detectedPitch.Volume * 8, 0, 1);

        if (!detectedPitch.HasPitch)
        {
            _lastDetectedDisplayMidiNote = null;
            DecayHoldProgress(DateTimeOffset.UtcNow);
            RenderExercise();
            MicrophoneStatusLabel.Text = detectedPitch.Volume < 0.012
                ? "Too quiet. Move closer or play a little stronger."
                : "Listening for a stable note...";
            return;
        }

        _lastDetectedDisplayMidiNote = detectedPitch.ClosestMidiNote - _exercise.SoundingTransposeSemitones;
        MicrophoneStatusLabel.Text = $"Heard {PitchMath.ToDisplayNoteName(detectedPitch.ClosestNoteName)} at {detectedPitch.FrequencyHz:0.0} Hz | confidence {detectedPitch.Confidence:P0}";
        var now = DateTimeOffset.UtcNow;
        var currentNote = _exercise.Notes[_currentNoteIndex];
        var centsFromTarget = PitchMath.CalculateCentsDifference(detectedPitch.FrequencyHz, currentNote.FrequencyHz);
        var isHeldPitch = detectedPitch.ClosestMidiNote == currentNote.MidiNote
            && Math.Abs(centsFromTarget) <= _settings.ToleranceCents;

        if (!isHeldPitch)
        {
            DecayHoldProgress(now);
            RenderExercise();
            return;
        }

        AddHoldProgress(now);
        RenderExercise();
        MicrophoneStatusLabel.Text = $"Hold steady: {_holdProgress:P0} of {GetHoldSeconds(_settings):0.0}s.";

        if (_holdProgress < 1)
        {
            return;
        }

        JudgeDetectedPitch(detectedPitch);
        ResetStableCandidate();
    }

    private void JudgeDetectedPitch(PitchDetectionResult detectedPitch)
    {
        if (_exercise is null || _settings is null || _currentNoteIndex >= _exercise.Notes.Count)
        {
            return;
        }

        var currentNote = _exercise.Notes[_currentNoteIndex];
        var result = _noteJudgmentService.Judge(currentNote, detectedPitch, _settings.ToleranceCents);

        JudgmentLabel.Text = result.Message;
        JudgmentLabel.TextColor = result.Judgment switch
        {
            NoteJudgmentType.Correct => GetColor("Primary"),
            NoteJudgmentType.TooSharp => GetColor("Tertiary"),
            NoteJudgmentType.TooFlat => GetColor("Tertiary"),
            NoteJudgmentType.WrongNote => GetColor("Tertiary"),
            _ => GetColor("Gray900")
        };

        DetectedPitchSummaryLabel.Text = detectedPitch.HasPitch
            ? $"Detected {PitchMath.ToDisplayNoteName(detectedPitch.ClosestNoteName)} at {detectedPitch.FrequencyHz:0.0} Hz."
            : "No pitch detected.";

        if (result.ShouldAdvance)
        {
            _sessionCorrectCount++;
            _currentNoteIndex++;

            if (_currentNoteIndex >= _exercise.Notes.Count)
            {
                _completedExerciseCount++;
                GenerateExercise(isAutoGenerated: true, resetSession: false);
                return;
            }
        }

        RefreshPracticeView();
    }

    private void OnGenerateExerciseClicked(object sender, EventArgs e)
    {
        GenerateExercise(isAutoGenerated: false, resetSession: true);
    }

    private void OnRestartExerciseClicked(object sender, EventArgs e)
    {
        if (_exercise is null)
        {
            GenerateExercise(isAutoGenerated: false, resetSession: true);
            return;
        }

        _currentNoteIndex = 0;
        _sessionCorrectCount = 0;
        _completedExerciseCount = 0;
        ResetStableCandidate();
        JudgmentLabel.Text = "Exercise restarted.";
        JudgmentLabel.TextColor = GetColor("Gray900");
        RefreshPracticeView();
    }

    private async void OnHomeClicked(object sender, EventArgs e)
    {
        await Shell.Current.GoToAsync("//home");
    }

    protected override async void OnDisappearing()
    {
        base.OnDisappearing();
        _isPageVisible = false;
        await StopListeningAsync();
    }

    private void ResetStableCandidate()
    {
        _lastDetectedDisplayMidiNote = null;
        _holdProgress = 0;
        _lastPitchUpdateAt = DateTimeOffset.MinValue;
    }

    private Color GetColor(string key)
    {
        return (Color)Application.Current!.Resources[key];
    }

    private static string GetBaseJumpLabel(PracticeOptionsConfig practiceOptions, InstrumentProfile instrument, int maxBaseNoteJump)
    {
        var labels = GetMaxJumpLabels(practiceOptions, instrument);
        return maxBaseNoteJump >= 0 && maxBaseNoteJump < labels.Count
            ? labels[maxBaseNoteJump]
            : labels.Last();
    }

    private static string GetAllowedBaseNotesLabel(PracticeSettings settings, InstrumentProfile instrument)
    {
        return settings.AllowedBaseNoteNames.Count == 0
            ? "all"
            : string.Join(", ", settings.AllowedBaseNoteNames.Select(noteName => PitchMath.ToAnchorLabel(noteName, instrument.BaseNoteItemSuffix)));
    }

    private static double GetHoldSeconds(PracticeSettings settings)
    {
        return 60d / Math.Clamp(settings.BeatTempoBpm, 1, 300);
    }

    private static string GetHoldRequirementLabel(PracticeSettings settings)
    {
        return $"hold {GetHoldSeconds(settings):0.0}s at {settings.BeatTempoBpm} BPM";
    }

    private static string GetAccidentalModeLabel(PracticeSettings settings)
    {
        if (!settings.AllowSharps)
        {
            return "natural notes only";
        }

        return settings.AvoidOpenStringSharps ? "no open-string sharps" : "sharps allowed";
    }

    private void AddHoldProgress(DateTimeOffset now)
    {
        if (_settings is null)
        {
            return;
        }

        var elapsedSeconds = GetElapsedPitchSeconds(now);
        var holdSeconds = GetHoldSeconds(_settings);
        _holdProgress = Math.Clamp(_holdProgress + (elapsedSeconds / holdSeconds), 0, 1);
    }

    private void DecayHoldProgress(DateTimeOffset now)
    {
        var elapsedSeconds = GetElapsedPitchSeconds(now);
        _holdProgress = Math.Clamp(_holdProgress - (elapsedSeconds * HoldProgressDecayPerSecond), 0, 1);
    }

    private double GetElapsedPitchSeconds(DateTimeOffset now)
    {
        if (_lastPitchUpdateAt == DateTimeOffset.MinValue)
        {
            _lastPitchUpdateAt = now;
            return 0;
        }

        var elapsedSeconds = Math.Clamp((now - _lastPitchUpdateAt).TotalSeconds, 0, 0.25d);
        _lastPitchUpdateAt = now;
        return elapsedSeconds;
    }

    private static List<string> GetMaxJumpLabels(PracticeOptionsConfig practiceOptions, InstrumentProfile instrument)
    {
        return practiceOptions.MaxTuningNoteJumpLabelsByInstrumentType.TryGetValue(instrument.InstrumentType, out var labels)
            ? labels
            : practiceOptions.MaxTuningNoteJumpLabelsByInstrumentType["string"];
    }
}
