using SightReadingHelper.Controls;
using SightReadingHelper.Models;
using SightReadingHelper.Services;

namespace SightReadingHelper;

public partial class PracticePage : ContentPage
{
    private const int SampleRate = 44100;

    private readonly PracticeDataService _practiceDataService;
    private readonly ExerciseGeneratorService _exerciseGeneratorService;
    private readonly PitchDetectionService _pitchDetectionService;
    private readonly PitchCalibrationService _pitchCalibrationService;
    private readonly NoteJudgmentService _noteJudgmentService;
    private readonly IAudioInputService _audioInputService;

    private InstrumentProfile? _instrument;
    private PracticeSettings? _settings;
    private PracticeOptionsConfig _practiceOptions = new();
    private CalibrationProfile? _calibration;
    private PracticeExercise? _exercise;
    private int _currentNoteIndex;
    private int _correctCount;
    private bool _isListening;
    private int? _stableCandidateMidiNote;
    private int? _lastDetectedDisplayMidiNote;
    private DateTimeOffset _stableCandidateStartedAt;
    private readonly StaffNotationDrawable _notationDrawable = new();

    public PracticePage(
        PracticeDataService practiceDataService,
        ExerciseGeneratorService exerciseGeneratorService,
        PitchDetectionService pitchDetectionService,
        PitchCalibrationService pitchCalibrationService,
        NoteJudgmentService noteJudgmentService,
        IAudioInputService audioInputService)
    {
        InitializeComponent();
        _practiceDataService = practiceDataService;
        _exerciseGeneratorService = exerciseGeneratorService;
        _pitchDetectionService = pitchDetectionService;
        _pitchCalibrationService = pitchCalibrationService;
        _noteJudgmentService = noteJudgmentService;
        _audioInputService = audioInputService;
        _audioInputService.SamplesAvailable += OnSamplesAvailable;
        NotationView.Drawable = _notationDrawable;
    }

    protected override async void OnAppearing()
    {
        base.OnAppearing();
        await LoadPracticeAsync();
    }

    private async Task LoadPracticeAsync()
    {
        _settings = await _practiceDataService.GetPracticeSettingsAsync();
        _practiceOptions = await _practiceDataService.GetPracticeOptionsAsync();
        _instrument = await _practiceDataService.GetSelectedInstrumentAsync();
        _calibration = await _practiceDataService.GetCalibrationAsync(_instrument.InstrumentName);

        PracticeSummaryLabel.Text = $"Active instrument: {_instrument.InstrumentName} ({_instrument.DefaultClef}).";
        PracticeSettingsLabel.Text = $"{_settings.ExerciseLength} notes, ±{_settings.ToleranceCents} cents, hold 1 beat at {_settings.BeatTempoBpm} BPM, {GetAccidentalModeLabel(_settings)}, {(_settings.UseBeginnerRange ? "beginner" : "full")} range, {GetBaseJumpLabel(_practiceOptions, _settings.MaxBaseNoteJump ?? 1).ToLowerInvariant()}, {_instrument.BaseNoteGroupLabel}: {GetAllowedBaseNotesLabel(_settings, _instrument)}.";

        if (_exercise is null || _exercise.InstrumentName != _instrument.InstrumentName || _exercise.Notes.Count != _settings.ExerciseLength)
        {
            GenerateExercise(isAutoGenerated: false);
        }
        else
        {
            RefreshPracticeView();
        }
    }

    private void GenerateExercise(bool isAutoGenerated)
    {
        if (_instrument is null || _settings is null)
        {
            return;
        }

        _exercise = _exerciseGeneratorService.GenerateExercise(_instrument, _settings);
        _currentNoteIndex = 0;
        _correctCount = 0;
        ResetStableCandidate();
        JudgmentLabel.Text = isAutoGenerated
            ? "Nice. Next exercise is ready."
            : "Exercise ready. Start listening, then play the highlighted note.";
        JudgmentLabel.TextColor = GetColor("Gray900");
        MusicXmlEditor.Text = _exercise.MusicXml;
        RefreshPracticeView();
    }

    private void RefreshPracticeView()
    {
        if (_exercise is null || _settings is null)
        {
            return;
        }

        RenderExercise();

        if (_currentNoteIndex >= _exercise.Notes.Count)
        {
            ExpectedPitchLabel.Text = $"Finished {_correctCount} of {_exercise.Notes.Count} notes.";
            DetectedPitchSummaryLabel.Text = "Generate another exercise or restart this one.";
            ProgressLabel.Text = $"Exercise complete. Score: {_correctCount}/{_exercise.Notes.Count}";
            ExerciseProgressBar.Progress = 1;
            return;
        }

        var currentNote = _exercise.Notes[_currentNoteIndex];
        ExpectedPitchLabel.Text = _settings.ShowNoteName
            ? $"Target: {PitchMath.ToDisplayNoteName(currentNote.DisplayNoteName)} | {currentNote.FrequencyHz:0.0} Hz"
            : $"Target pitch: {currentNote.FrequencyHz:0.0} Hz";
        DetectedPitchSummaryLabel.Text = _isListening
            ? $"Listening for a stable pitch. Hold each note for {GetHoldSeconds(_settings):0.0}s."
            : "Press Start Listening when you are ready to play.";
        ProgressLabel.Text = $"Note {_currentNoteIndex + 1} of {_exercise.Notes.Count} | Correct: {_correctCount}";
        ExerciseProgressBar.Progress = _exercise.Notes.Count == 0
            ? 0
            : (double)_currentNoteIndex / _exercise.Notes.Count;
    }

    private void RenderExercise()
    {
        if (_exercise is null)
        {
            return;
        }

        _notationDrawable.Notes = _exercise.Notes;
        _notationDrawable.Clef = _exercise.Clef;
        _notationDrawable.CurrentNoteIndex = _currentNoteIndex;
        _notationDrawable.GhostMidiNote = _lastDetectedDisplayMidiNote;
        NotationView.WidthRequest = StaffNotationDrawable.GetRequiredWidth(_exercise.Notes.Count);
        NotationView.Invalidate();
    }

    private async void OnStartListeningClicked(object sender, EventArgs e)
    {
        if (_isListening)
        {
            return;
        }

        try
        {
            ResetStableCandidate();
            await _audioInputService.StartAsync(SampleRate);
            _isListening = true;
            StartListeningButton.IsEnabled = false;
            StopListeningButton.IsEnabled = true;
            MicrophoneStatusLabel.Text = "Listening...";
            RefreshPracticeView();
        }
        catch (Exception ex)
        {
            MicrophoneStatusLabel.Text = "Could not start the microphone.";
            await DisplayAlert("Microphone error", ex.Message, "OK");
        }
    }

    private async void OnStopListeningClicked(object sender, EventArgs e)
    {
        await StopListeningAsync();
    }

    private async Task StopListeningAsync()
    {
        if (!_isListening)
        {
            return;
        }

        await _audioInputService.StopAsync();
        _isListening = false;
        StartListeningButton.IsEnabled = true;
        StopListeningButton.IsEnabled = false;
        MicrophoneStatusLabel.Text = "Stopped.";
        ResetStableCandidate();
        RefreshPracticeView();
    }

    private void OnSamplesAvailable(float[] samples, int sampleRate)
    {
        var rawDetectedPitch = _pitchDetectionService.AnalyzeSamples(samples, sampleRate);
        var detectedPitch = _pitchCalibrationService.ApplyCalibration(rawDetectedPitch, _calibration);
        MainThread.BeginInvokeOnMainThread(() => HandleDetectedPitch(detectedPitch));
    }

    private void HandleDetectedPitch(PitchDetectionResult detectedPitch)
    {
        if (!_isListening || _exercise is null || _settings is null || _currentNoteIndex >= _exercise.Notes.Count)
        {
            return;
        }

        MicrophoneLevelBar.Progress = Math.Clamp(detectedPitch.Volume * 8, 0, 1);

        if (!detectedPitch.HasPitch)
        {
            _lastDetectedDisplayMidiNote = null;
            RenderExercise();
            MicrophoneStatusLabel.Text = detectedPitch.Volume < 0.012
                ? "Too quiet. Move closer or play a little stronger."
                : "Listening for a stable note...";
            return;
        }

        _lastDetectedDisplayMidiNote = detectedPitch.ClosestMidiNote - _exercise.SoundingTransposeSemitones;
        RenderExercise();
        MicrophoneStatusLabel.Text = $"Heard {PitchMath.ToDisplayNoteName(detectedPitch.ClosestNoteName)} at {detectedPitch.FrequencyHz:0.0} Hz | confidence {detectedPitch.Confidence:P0}";

        if (_stableCandidateMidiNote != detectedPitch.ClosestMidiNote)
        {
            _stableCandidateMidiNote = detectedPitch.ClosestMidiNote;
            _stableCandidateStartedAt = DateTimeOffset.UtcNow;
            return;
        }

        if (DateTimeOffset.UtcNow - _stableCandidateStartedAt < GetStablePitchWindow(_settings))
        {
            return;
        }

        JudgeDetectedPitch(detectedPitch);
        ResetStableCandidate();
    }

    private void JudgeDetectedPitch(PitchDetectionResult detectedPitch)
    {
        if (_exercise is null || _settings is null || _currentNoteIndex >= _exercise.Notes.Count)
        {
            return;
        }

        var currentNote = _exercise.Notes[_currentNoteIndex];
        var result = _noteJudgmentService.Judge(currentNote, detectedPitch, _settings.ToleranceCents);

        JudgmentLabel.Text = result.Message;
        JudgmentLabel.TextColor = result.Judgment switch
        {
            NoteJudgmentType.Correct => GetColor("Primary"),
            NoteJudgmentType.TooSharp => GetColor("Tertiary"),
            NoteJudgmentType.TooFlat => GetColor("Tertiary"),
            NoteJudgmentType.WrongNote => GetColor("Tertiary"),
            _ => GetColor("Gray900")
        };

        DetectedPitchSummaryLabel.Text = detectedPitch.HasPitch
            ? $"Detected {PitchMath.ToDisplayNoteName(detectedPitch.ClosestNoteName)} at {detectedPitch.FrequencyHz:0.0} Hz."
            : "No pitch detected.";

        if (result.ShouldAdvance)
        {
            _correctCount++;
            _currentNoteIndex++;

            if (_currentNoteIndex >= _exercise.Notes.Count)
            {
                GenerateExercise(isAutoGenerated: true);
                return;
            }
        }

        RefreshPracticeView();
    }

    private void OnGenerateExerciseClicked(object sender, EventArgs e)
    {
        GenerateExercise(isAutoGenerated: false);
    }

    private void OnRestartExerciseClicked(object sender, EventArgs e)
    {
        if (_exercise is null)
        {
            GenerateExercise(isAutoGenerated: false);
            return;
        }

        _currentNoteIndex = 0;
        _correctCount = 0;
        ResetStableCandidate();
        JudgmentLabel.Text = "Exercise restarted.";
        JudgmentLabel.TextColor = GetColor("Gray900");
        RefreshPracticeView();
    }

    protected override async void OnDisappearing()
    {
        base.OnDisappearing();
        await StopListeningAsync();
    }

    private void ResetStableCandidate()
    {
        _stableCandidateMidiNote = null;
        _lastDetectedDisplayMidiNote = null;
        _stableCandidateStartedAt = DateTimeOffset.MinValue;
    }

    private Color GetColor(string key)
    {
        return (Color)Application.Current!.Resources[key];
    }

    private static string GetBaseJumpLabel(PracticeOptionsConfig practiceOptions, int maxBaseNoteJump)
    {
        return maxBaseNoteJump >= 0 && maxBaseNoteJump < practiceOptions.MaxStringJumpLabels.Count
            ? practiceOptions.MaxStringJumpLabels[maxBaseNoteJump]
            : practiceOptions.MaxStringJumpLabels.Last();
    }

    private static string GetAllowedBaseNotesLabel(PracticeSettings settings, InstrumentProfile instrument)
    {
        return settings.AllowedBaseNoteNames.Count == 0
            ? "all"
            : string.Join(", ", settings.AllowedBaseNoteNames.Select(noteName => PitchMath.ToAnchorLabel(noteName, instrument.BaseNoteItemSuffix)));
    }

    private static TimeSpan GetStablePitchWindow(PracticeSettings settings)
    {
        return TimeSpan.FromSeconds(GetHoldSeconds(settings));
    }

    private static double GetHoldSeconds(PracticeSettings settings)
    {
        return 60d / Math.Clamp(settings.BeatTempoBpm, 1, 300);
    }

    private static string GetAccidentalModeLabel(PracticeSettings settings)
    {
        if (!settings.AllowSharps)
        {
            return "natural notes only";
        }

        return settings.AvoidOpenStringSharps ? "no open-string sharps" : "sharps allowed";
    }
}
